// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProcessHelper.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Process.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Process.Recipes
{
    using OBeautifulCode.Assertion.Recipes;

    /// <summary>
    /// Contains helper/convenience methods related to managing processes.
    /// </summary>
#if !OBeautifulCodeProcessRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Process.Recipes", "See package version number")]
    internal
#else
    public
#endif
    static class ProcessHelpers
    {
    }
}
